version: "3"

services:
  nginx:
    image: registry.cn-shenzhen.aliyuncs.com/a852203465/nginx:1.25.2a
    container_name: nginx
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      NGINX_LOG_DAYS: 1
    volumes:
      - ./logs:/var/log/nginx
    expose:
      - 80
    ports:
      - "8000:80"
    networks:
      - nginx_net

networks:
  nginx_net:
    external: true





